# Generated by Django 4.0.4 on 2022-05-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_core_level_alter_core_click_power_alter_core_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boost',
            name='level',
        ),
    ]
