# Generated by Django 4.0.4 on 2022-06-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_boost_type_core_auto_click_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boost',
            name='type',
        ),
        migrations.RemoveField(
            model_name='core',
            name='auto_click_power',
        ),
    ]
